In [1]:
import sys
sys.path.append("D:\work\models-master")
import tensorflow as tf
import run_classifier
import bert_models
from official.nlp.bert import configs as bert_configs
import json

In [2]:
bert_config_path=r"D:\work\models-master\official\nlp\process_dir\models\hub_config\bert_config.json"
bert_config = bert_configs.BertConfig.from_json_file(bert_config_path)

with tf.io.gfile.GFile(r"D:\work\models-master\official\nlp\bert\model_dir\output\_meta_data", 'rb') as reader:
    input_meta_data = json.loads(reader.read().decode('utf-8'))

In [3]:
model1, model2 = bert_models.classifier_model(bert_config, 16,128)

Note that input tensors are instantiated via `tensor = tf.keras.Input(shape)`.
The tensor that caused the issue was: input_mask:0
Note that input tensors are instantiated via `tensor = tf.keras.Input(shape)`.
The tensor that caused the issue was: input_type_ids:0


In [4]:
train_input_fn = run_classifier.get_dataset_fn(r"D:\work\models-master\official\nlp\bert\model_dir\output\bdbk_train.tf_record",
                                              128, 8, is_training=True)

In [5]:
ds = train_input_fn()

In [6]:
it = ds.__iter__()

In [7]:
inp = it.next()

In [8]:
inp

({'input_word_ids': <tf.Tensor: shape=(8, 128), dtype=int32, numpy=
  array([[ 101, 3289, 7473, ...,    0,    0,    0],
         [ 101, 1723, 2658, ...,  117,  794,  102],
         [ 101, 2144, 5310, ..., 2519, 3119,  102],
         ...,
         [ 101, 1062, 1385, ..., 2157, 3184,  102],
         [ 101, 2002, 1392, ...,  671,  510,  102],
         [ 101,  741, 1399, ..., 4995, 5688,  102]])>,
  'input_mask': <tf.Tensor: shape=(8, 128), dtype=int32, numpy=
  array([[1, 1, 1, ..., 0, 0, 0],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         ...,
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1],
         [1, 1, 1, ..., 1, 1, 1]])>,
  'input_type_ids': <tf.Tensor: shape=(8, 128), dtype=int32, numpy=
  array([[0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         ...,
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0],
         [0, 0, 0, ..., 0, 0, 0]])>},
 <tf.Tensor: shape=(8,), dty

In [26]:
input_meta_data["labels_list"][4]

'webfic'

In [9]:
model1.load_weights(r"D:\work\models-master\official\nlp\bert\model_dir\output\checkpoint")

In [10]:
tf.argmax(model1.call(inp), axis=1)

<tf.Tensor: shape=(8,), dtype=int64, numpy=array([7, 7, 7, 7, 7, 7, 7, 7], dtype=int64)>

ValueError: Unknown layer: BertClassifier